{{- /* Copyright 2020 Hewlett Packard Enterprise Development LP */ -}}

{{- define "cray-nexus-setup.blobStores" -}}

  {{- $blobStores := list -}}
  {{- if .Values.s3.enabled -}}
    {{- $blobStores = concat $blobStores (values .Values.blobStores.s3) -}}
  {{- else -}}
    {{- $blobStores = concat $blobStores (values .Values.blobStores.file) -}}
  {{- end -}}
  {{- $blobStores = concat (compact $blobStores) (compact .Values.additionalBlobStores) -}}

  {{- range $blobStores -}}
    {{- include "cray-nexus-setup.blobStore" . -}}
  {{- end -}}

{{- end -}}
