#!/usr/bin/env bash

# Copyright 2022 Hewlett Packard Enterprise Development LP

export PATH="$PATH:$(dirname "$0")/../bin"

set -x

# Configure curl authentication
export CURL_HOME="$(mktemp -d)"
trap "rm -fr '$CURL_HOME'" EXIT

export NEXUS_PASSWORD=adminpwd
nexus-curl-auth "$CURL_HOME"

while ! nexus-ready; do
  echo >&2 "trying again in 10 seconds"
  sleep 10
done

set -e

nexus-upload-script $(dirname "$0")/../groovy/*.groovy >&2
nexus-enable-keycloak-realm >&2
nexus-enable-docker-realm >&2
nexus-enable-rut-auth >&2
nexus-enable-anonymous-access >&2
