#!/usr/bin/env bash

# Copyright 2022 Hewlett Packard Enterprise Development LP

export PATH="$PATH:$(dirname "$0")/../bin"
export NEXUS_USERNAME=admin
export NEXUS_PASSWORD=adminpwd

set -x

while ! nexus-ready; do
  echo >&2 "trying again in 10 seconds"
  sleep 10
done

set -e

. "$(command -v nexus-ready)"

nexus-upload-script $(dirname "$0")/../groovy/*.groovy >&2
nexus-enable-keycloak-realm >&2
nexus-enable-docker-realm >&2
nexus-enable-rut-auth >&2
nexus-enable-anonymous-access >&2
