#!/usr/bin/env bash

# Copyright 2022 Hewlett Packard Enterprise Development LP

export PATH="$PATH:$(dirname "$0")/../bin"

set -x

while ! nexus-ready; do
  echo >&2 "trying again in 10 seconds"
  sleep 10
done

set -e

. "$(command -v nexus-ready)"

# Change default admin password, as necessary
if curl -sfk "${URL}/v1/status/check"; then
    echo adminpwd | nexus-change-password admin >&2
fi
