# Copyright 2020 Hewlett Packard Enterprise Development LP

nameOverride: ""
fullnameOverride: ""

image:
  repository: dtr.dev.cray.com/cray/cray-nexus-setup
  tag: 0.3.2
  pullPolicy: IfNotPresent

nexusService: nexus

kubectl:
  image:
    repository: dtr.dev.cray.com/loftsman/loftsman
    tag: latest
    pullPolicy: IfNotPresent

s3:
  enabled: false
  secret: nexus-s3-credentials
  endpointUrl: http://cray-s3.ceph-rgw.svc.cluster.local:8080
  srcSecret:
    namespace: default
    name: nexus-s3-credentials

adminCredentials:
  enabled: false
  secret: nexus-admin-credentials

# Curated blob stores: Either s3 OR file blob stores are created based on
# `s3.enabled`.
blobStores:
  file:
    latest:
      name: latest
    shasta-1.3:
      name: shasta-1.3
  s3:
    latest:
      name: latest
      bucketConfiguration:
        bucket:
          name: nexus
    shasta-1.3:
      name: shasta-1.3
      bucketConfiguration:
        bucket:
          name: nexus

# Additional blob stores to be setup regardless of `s3.enabled`.
additionalBlobStores: []

repositories:

  container-images:
    shasta-1.3:
      name: registry-1.3
      format: docker
      storage:
        blobStoreName: shasta-1.3
        writePolicy: ALLOW
      docker:
        # Port must be exposed by cray-nexus.service
        httpPort: 5003

  # Note: Support for helm group repositories is still open, see
  # https://issues.sonatype.org/browse/NEXUS-22807
  helm-charts:
    shasta-1.3:
      name: charts-1.3
      format: helm
      storage:
        blobStoreName: shasta-1.3

  mirror-sle-15sp1-all-products:
    latest:
      name: mirror-sle-15sp1-all-products
      format: yum
      storage:
        blobStoreName: latest
      group:
        memberNames:
        - mirror-1.3-sle-15sp1-all-products
      _weight: 40
    shasta-1.3:
      name: mirror-1.3-sle-15sp1-all-products
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - mirror-1.3.0-sle-15sp1-all-products
      _weight: 20
    shasta-1.3.0:
      name: mirror-1.3.0-sle-15sp1-all-products
      format: yum
      storage:
        blobStoreName: shasta-1.3

  mirror-sle-15sp1-all-updates:
    latest:
      name: mirror-sle-15sp1-all-updates
      format: yum
      storage:
        blobStoreName: latest
      group:
        memberNames:
        - mirror-1.3-sle-15sp1-all-updates
      _weight: 40
    shasta-1.3:
      name: mirror-1.3-sle-15sp1-all-updates
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - mirror-1.3.0-sle-15sp1-all-updates
      _weight: 20
    shasta-1.3.0:
      name: mirror-1.3.0-sle-15sp1-all-updates
      format: yum
      storage:
        blobStoreName: shasta-1.3

  mirror-opensuse-leap-15:
    latest:
      name: mirror-opensuse-leap-15
      format: yum
      storage:
        blobStoreName: latest
      group:
        memberNames:
        - mirror-1.3-opensuse-leap-15
      _weight: 40
    shasta-1.3:
      name: mirror-1.3-opensuse-leap-15
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - mirror-1.3.0-opensuse-leap-15
      _weight: 20
    shasta-1.3.0:
      name: mirror-1.3.0-opensuse-leap-15
      format: yum
      storage:
        blobStoreName: shasta-1.3

  badger:
    shasta-1.3:
      name: badger-1.3
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - badger-1.3.0
      _weight: 20
    shasta-1.3.0:
      name: badger-1.3.0
      format: yum
      storage:
        blobStoreName: shasta-1.3

  cos-sle-15sp1-compute:
    shasta-1.3:
      name: cos-1.3-sle-15sp1-compute
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - cos-1.3.0-sle-15sp1-compute
      _weight: 20
    shasta-1.3.0:
      name: cos-1.3.0-sle-15sp1-compute
      format: yum
      storage:
        blobStoreName: shasta-1.3

  cos-sle-15sp1-management:
    shasta-1.3:
      name: cos-1.3-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - cos-1.3.0-sle-15sp1-management
      _weight: 20
    shasta-1.3.0:
      name: cos-1.3.0-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3

  cos-images-sle-15sp1-compute:
    shasta-1.3:
      name: cos-images-1.3-sle-15sp1-compute
      format: raw
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - cos-images-1.3.0-sle-15sp1-compute
      _weight: 20
    shasta-1.3.0:
      name: cos-images-1.3.0-sle-15sp1-compute
      format: raw
      storage:
        blobStoreName: shasta-1.3

  ct-tests-sle-15sp1-management:
    shasta-1.3:
      name: ct-tests-1.3-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - ct-tests-1.3.0-sle-15sp1-management
      _weight: 20
    shasta-1.3.0:
      name: ct-tests-1.3.0-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3

  shasta-firmware:
    shasta-1.3:
      name: shasta-firmware-1.3
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - shasta-firmware-1.3.0
      _weight: 20
    shasta-1.3.0:
      name: shasta-firmware-1.3.0
      format: yum
      storage:
        blobStoreName: shasta-1.3

  thirdparty-sle-15sp1-compute:
    shasta-1.3:
      name: thirdparty-1.3-sle-15sp1-compute
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - thirdparty-1.3.0-sle-15sp1-compute
      _weight: 20
    shasta-1.3.0:
      name: thirdparty-1.3.0-sle-15sp1-compute
      format: yum
      storage:
        blobStoreName: shasta-1.3

  thirdparty-sle-15sp1-management:
    shasta-1.3:
      name: thirdparty-1.3-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - thirdparty-1.3.0-sle-15sp1-management
      _weight: 20
    shasta-1.3.0:
      name: thirdparty-1.3.0-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3

  sma-sle-15sp1-compute:
    shasta-1.3:
      name: sma-1.3-sle-15sp1-compute
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - sma-1.3.0-sle-15sp1-compute
      _weight: 20
    shasta-1.3.0:
      name: sma-1.3.0-sle-15sp1-compute
      format: yum
      storage:
        blobStoreName: shasta-1.3

  sma-sle-15sp1-management:
    shasta-1.3:
      name: sma-1.3-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - sma-1.3.0-sle-15sp1-management
      _weight: 20
    shasta-1.3.0:
      name: sma-1.3.0-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3

  sma-crayctldeploy-sle-15sp1-management:
    shasta-1.3:
      name: sma-crayctldeploy-1.3-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - sma-crayctldeploy-1.3.0-sle-15sp1-management
      _weight: 20
    shasta-1.3.0:
      name: sma-crayctldeploy-1.3.0-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3

  sms-crayctldeploy-sle-15sp1-management:
    shasta-1.3:
      name: sms-crayctldeploy-1.3-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3
      group:
        memberNames:
        - sms-crayctldeploy-1.3.0-sle-15sp1-management
      _weight: 20
    shasta-1.3.0:
      name: sms-crayctldeploy-1.3.0-sle-15sp1-management
      format: yum
      storage:
        blobStoreName: shasta-1.3

# Additional repositories to setup
additionalRepositories: []
